In [5]:
import numpy as np
image=np.array([[1,2,3],
               [4,5,6],
                [7,8,9]])
image=np.transpose(image)
print(image)

image[:, [0,2]]=image[:,[2,0]]
print(image)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[7 4 1]
 [8 5 2]
 [9 6 3]]
